name: Build and Deploy

on:
  push:
    branches:
      - master/**
      - subwallet/**
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag
        default: accounts-react 
      is_latest:
        type: boolean
        description: also push latest tag
        default: true

jobs:
  build:
    name: Build and push Docker Image
    uses: UniqueNetwork/web-deploy/.github/workflows/build-docker-image.yml@master
    secrets: inherit
    with:
      tag: accounts-react
      dockerfile: ./Dockerfile
      target: static
      is_latest: ${{ github.event.inputs.is_latest }}

# todo: implement, just a placeholder for now
  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Deploying"
